### ISSUE TITLE
async support required??

### ISSUE THREAD

**Issue by azz0r** [reactopt/reactopt#71]
gl06449m:fs aaron.lote$ npm run reactopt localhost:3000

> fed-simulator@5.0.0 reactopt /Users/aaron.lote/Sites/Reference/fs
> node node_modules/reactopt/main.js "localhost:3000"

/Users/aaron.lote/Sites/Reference/fs/node_modules/reactopt/main.js:35
puppeteer.launch({headless: false}).then(async browser => {
                                         ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fed-simulator@5.0.0 reactopt: `node node_modules/reactopt/main.js "localhost:3000"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fed-simulator@5.0.0 reactopt script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aaron.lote/.npm/_logs/2017-12-04T16_50_49_370Z-debug.log

**Comment by itspamlam** [comment]
@azz0r We've updated our readme to mention that we do utilize async/await which is natively supported by Node 7.6+.
